---
name: Check Docusaurus Build
on: push

jobs:
  check-build:
    runs-on: selfhosted
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: v18.18.0
          cache: npm

      - name: Cache Node.js packages
        id: cache-npm
        uses: actions/cache@v3.3.2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install Dependencies
        run: npm ci

      - name: Build Docusaurus
        run: npm run build 2> >(tee build.error)

      - name: Check if build has warnings
        run: cat build.error | grep "\[WARNING\]" && echo "::error::Fix the warnings" && exit 1  || exit 0
